### ISSUE TITLE
Update Minimal RAM Check.

### ISSUE THREAD

**Issue by bhoefer2015** [RedHatSatellite/satellite-sanity#51]
The sanity script still considers "12582912 kB" to be the minimum RAM needed for Satellite.  That is no longer true as of Satellite 6.3; it was changed to 20 GiB.  (20 GiB is still the minimum as of Satellite 6.5.)  Please see:

https://access.redhat.com/documentation/en-us/red_hat_satellite/6.3/html/installation_guide/preparing_your_environment_for_installation#system_requirements

**Comment by jhutar** [comment]
Hello. Please note we do not plan any extra work being done on this project. Sanity checks for Foreman and Satellite 6 are currently gathered in this tool: https://github.com/theforeman/foreman_maintain (also packaged for Sat6).
